{{- if .Values.cronjobs.enabled }}

{{- range $jobName, $job := .Values.cronjobs.jobs }}

{{- if $job.enabled }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "django-app.fullname" $ }}-job-{{ $jobName | nospace | lower | replace "_" "-" }}
  labels:
    app: {{ include "django-app.fullname" $ }}
    component: cronjob
    jobName: {{ $jobName }}
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
spec:
  schedule: {{ $job.schedule | quote }}
  {{- if $job.timeZone }}
  timeZone: {{ $job.timeZone | quote }}
  {{- end }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ default 7200 $job.timeLimit }}  # 2 hours default
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: cronjob
              command:
                {{- toYaml $job.command | nindent 16 }}
              {{- include "django-app.imageConfig"
                  (dict "Default" $.Values.image "Override" $.Values.cronjobs.image)
                  | nindent 14
              }}
              resources:
                {{- include "django-app.resourcesConfig"
                    (dict "Default" $.Values.cronjobs.defaultResources "Override" $job.resources)
                    | nindent 16
                }}
              envFrom:
                {{- include "django-app.envFromTemplate" $ | nindent 16 }}
              env:
                {{- include "django-app.envTemplate"
                    (dict "Values" $.Values "Type" "cronjob" )
                    | nindent 16
                }}

{{- end }}

{{- end }}

{{- end }}
