apiVersion: v2
name: banjo-helm
description: "Helm Chart to deploy the Django application"
type: application
version: 0.4.0-dev1  # managed by release.sh
# Native lifecycle.preStop.sleep action went GA in K8s 1.30.
kubeVersion: ">= 1.30.0-0"
sources:
  - https://github.com/toggle-corp/charts
