{{- if not .Values.secretsStoreCsiDriver.create -}}

kind: Secret
apiVersion: v1
metadata:
  name: {{ template "banjo.secretname" . }}
  {{- with (include "banjo.resourceAnnotations" (dict "Context" $)) -}}{{ . | nindent 2 }}{{- end }}
  labels:
    app: {{ include "banjo.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
    {{- with (include "banjo.commonLabels" $) -}}{{ . | nindent 4 }}{{- end }}
type: Opaque
stringData:
  # secrets
  {{- range $name, $value := .Values.secrets }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $name }}: {{ (kindIs "string" $value) | ternary (tpl (toString $value) $) (toJson $value) | quote }}
  {{- end }}
  {{- end }}

{{- end }}
