{{- if .Values.secretsStoreCsiDriver.create -}}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "banjo.secretProviderName" . }}
  {{- with (include "banjo.resourceAnnotations" (dict "Context" $)) -}}{{ . | nindent 2 }}{{- end }}
  {{- with (include "banjo.resourceLabels" (dict "Context" $)) }}
  labels:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ .Values.secretsStoreCsiDriver.provider }}
  parameters:
    {{- with .Values.secretsStoreCsiDriver.parameters -}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    objects: |
      array:
      {{- range $secret_key, $object_key := .Values.secretsStoreCsiDriver.secretsKeyMap }}
        - |
          objectName: {{ $object_key }}
          objectType: secret
      {{- end }}
  secretObjects:
    - secretName: {{ template "banjo.secretname" . }}
      type: Opaque
      data:
      {{- range $secret_key, $object_key := .Values.secretsStoreCsiDriver.secretsKeyMap }}
        - objectName: {{ $object_key }}
          key: {{ $secret_key }}
      {{- end }}

{{- end }}
