{{- if .Values.serviceAccount.create -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "banjo.serviceAccountName" . }}
  {{- with (include "banjo.resourceAnnotations" (dict "Override" .Values.serviceAccount.annotations "Context" $)) -}}{{ . | nindent 2 }}{{- end }}
  {{- $saLabels := deepCopy (default (dict) .Values.commonLabels) -}}
  {{- range $k, $v := (default (dict) .Values.serviceAccount.labels) }}{{- $_ := set $saLabels $k $v -}}{{- end }}
  {{- with (include "banjo.tplAnnotations" (dict "Annotations" $saLabels "Context" $)) }}
  labels:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}

{{- end }}
