{{- if .Values.api.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "banjo.fullname" . }}-api
  {{- with (include "banjo.resourceAnnotations" (dict "Context" $)) -}}{{ . | nindent 2 }}{{- end }}
  labels:
    app: {{ include "banjo.fullname" . }}
    component: api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
    {{- with (include "banjo.commonLabels" $) -}}{{ . | nindent 4 }}{{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "banjo.fullname" . }}
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.api.containerPort }}

{{- end }}
