{{- if .Values.serviceAccount.create -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "banjo.serviceAccountName" . }}
  {{- with (include "banjo.tplAnnotations" (dict "Annotations" .Values.serviceAccount.annotations "Context" $)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
  {{- with (include "banjo.tplAnnotations" (dict "Annotations" .Values.serviceAccount.labels "Context" $)) }}
  labels:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}

{{- end }}
