{{- if .Values.worker.enabled }}
{{- if .Values.worker.flower.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "django-app.fullname" . }}-celery-flower
  labels:
    app: {{ include "django-app.fullname" . }}
    component: worker-flower
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "django-app.fullname" . }}
      component: worker-flower
  template:
    metadata:
      annotations:
        {{- include "django-app.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "django-app.fullname" . }}
        component: worker-flower
    spec:
      containers:
        - name: worker
          {{- include "django-app.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.worker.flower.image)
              | nindent 10
          }}
          command:
            {{- toYaml .Values.worker.flower.command | nindent 12 }}
          # TODO: livenessProbe
          resources:
            {{- toYaml .Values.worker.flower.resources | nindent 12 }}
          envFrom:
            {{- include "django-app.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "django-app.envTemplate"
                (dict "Values" $.Values "Type" "worker" )
                | nindent 12
            }}

{{- end }}
{{- end }}
