{{- if .Values.api.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "django-app.fullname" . }}-api
  labels:
    app: {{ include "django-app.fullname" . }}
    component: api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "django-app.fullname" . }}
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.api.containerPort }}

{{- end }}
