---
# Source: banjo-helm/templates/api/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-account
  annotations:
    
    azure.workload.identity/client-id: XXXXXXXX-YYYYYYYY
  labels:
    
    azure.workload.identity/use: "true"
automountServiceAccountToken: true
---
# Source: banjo-helm/templates/config/secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: release-name-banjo-helm-secret
  labels:
    app: release-name-banjo-helm
    environment: ALPHA
    release: release-name
type: Opaque
stringData:
  # secrets
  AWS_S3_ACCESS_KEY_ID: "minio-user"
  AWS_S3_AWS_ENDPOINT_URL: "https://myapp-minio.example.com/"
  AWS_S3_BUCKET_MEDIA_NAME: "media-data"
  AWS_S3_BUCKET_STATIC_NAME: "static-data"
  AWS_S3_REGION: "us-east-1"
  AWS_S3_SECRET_ACCESS_KEY: "random-strong-password"
  POSTGRES_DB: "my-app"
  POSTGRES_HOST: "my-app-postgres"
  POSTGRES_PASSWORD: "random-strong-password"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  REDIS_URL: "redis://my-app-redis-master:6379/0"
---
# Source: banjo-helm/templates/config/configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: release-name-banjo-helm-env-name
  labels:
    app: release-name-banjo-helm
    environment: ALPHA
    release: release-name
data:
  # Configs
  ENV_1: "VALUE_1"
---
# Source: banjo-helm/templates/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-banjo-helm-api
  labels:
    app: release-name-banjo-helm
    component: api
    environment: ALPHA
    release: release-name
spec:
  type: ClusterIP
  selector:
    app: release-name-banjo-helm
    component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Source: banjo-helm/templates/worker-addons/service.yaml
# Addon Service: flower
apiVersion: v1
kind: Service
metadata:
  name: release-name-banjo-helm-worker-flower
  labels:
    app: release-name-banjo-helm
    component: worker-addon
    addon: flower
    environment: ALPHA
    release: release-name
spec:
  type: ClusterIP
  selector:
    app: release-name-banjo-helm
    component: worker-addon
    addon: flower
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
# Source: banjo-helm/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-banjo-helm-api
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-banjo-helm
    component: api
    environment: ALPHA
    release: release-name
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-banjo-helm
      component: api
  template:
    metadata:
      annotations:
        checksum/secret: 66a6fc24b76971f276c49234b716b2b8226b4c72a18511215a54ab9a414b4d53
        checksum/configmap: 3f5505b0f56b1094e754509a8dd06e18d87db0905c755ea4b4ab0cc647f29da3
      labels:
        app: release-name-banjo-helm
        component: api
    spec:
      serviceAccountName: secret-account
      terminationGracePeriodSeconds: 38
      containers:
        - name: api
          image: "ghcr.io/example/example:v1.0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          envFrom:
            - secretRef:
                name: release-name-banjo-helm-secret
            - configMapRef:
                name: release-name-banjo-helm-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "web"
            
          lifecycle:
            preStop:
              sleep:
                seconds: 8
---
# Source: banjo-helm/templates/worker-addons/deployment.yaml
# Addon: beat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-banjo-helm-worker-beat
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-banjo-helm
    component: worker-addon
    addon: beat
    environment: ALPHA
    release: release-name
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-banjo-helm
      component: worker-addon
      addon: beat
  template:
    metadata:
      annotations:
        checksum/secret: 66a6fc24b76971f276c49234b716b2b8226b4c72a18511215a54ab9a414b4d53
        checksum/configmap: 3f5505b0f56b1094e754509a8dd06e18d87db0905c755ea4b4ab0cc647f29da3
      labels:
        app: release-name-banjo-helm
        component: worker-addon
        addon: beat
    spec:
      serviceAccountName: secret-account
      containers:
        - name: beat
          image: "ghcr.io/example/example:v1.0.1"
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - myapp
            - beat
            - -l
            - INFO
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: release-name-banjo-helm-secret
            - configMapRef:
                name: release-name-banjo-helm-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "worker"
---
# Source: banjo-helm/templates/worker-addons/deployment.yaml
# Addon: flower
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-banjo-helm-worker-flower
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-banjo-helm
    component: worker-addon
    addon: flower
    environment: ALPHA
    release: release-name
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-banjo-helm
      component: worker-addon
      addon: flower
  template:
    metadata:
      annotations:
        checksum/secret: 66a6fc24b76971f276c49234b716b2b8226b4c72a18511215a54ab9a414b4d53
        checksum/configmap: 3f5505b0f56b1094e754509a8dd06e18d87db0905c755ea4b4ab0cc647f29da3
      labels:
        app: release-name-banjo-helm
        component: worker-addon
        addon: flower
    spec:
      serviceAccountName: secret-account
      containers:
        - name: flower
          image: "ghcr.io/example/example:v1.0.1"
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - myapp
            - flower
            - --port=8000
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: release-name-banjo-helm-secret
            - configMapRef:
                name: release-name-banjo-helm-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "worker"
---
# Source: banjo-helm/templates/worker/deployment.yaml
# Queue: default
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-banjo-helm-worker-default
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: release-name-banjo-helm
    component: worker
    queue: default
    environment: ALPHA
    release: release-name
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: release-name-banjo-helm
      component: worker
      queue: default
  template:
    metadata:
      annotations:
        checksum/secret: 66a6fc24b76971f276c49234b716b2b8226b4c72a18511215a54ab9a414b4d53
        checksum/configmap: 3f5505b0f56b1094e754509a8dd06e18d87db0905c755ea4b4ab0cc647f29da3
      labels:
        app: release-name-banjo-helm
        component: worker
        queue: default
    spec:
      serviceAccountName: secret-account
      containers:
        - name: worker
          command:
            - celery
            - -A
            - myapp
            - worker
            - -l
            - INFO
            - -Q
            - celery
          image: "ghcr.io/example/example:v1.0.1"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: "0.1"
              memory: 256Mi
          envFrom:
            - secretRef:
                name: release-name-banjo-helm-secret
            - configMapRef:
                name: release-name-banjo-helm-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "worker"
---
# Source: banjo-helm/templates/hooks/job.yaml
# Hook: collect-static
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-banjo-helm-collect-static
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: release-name-banjo-helm
    component: hook
    hookName: collect-static
    environment: ALPHA
    release: release-name
spec:
  template:
    metadata:
      annotations:
        checksum/secret: 66a6fc24b76971f276c49234b716b2b8226b4c72a18511215a54ab9a414b4d53
        checksum/configmap: 3f5505b0f56b1094e754509a8dd06e18d87db0905c755ea4b4ab0cc647f29da3
      labels:
        app: release-name-banjo-helm
        component: hook
        hookName: collect-static
    spec:
      restartPolicy: "Never"
      serviceAccountName: secret-account
      containers:
        - name: collect-static
          image: "ghcr.io/example/example:v1.0.1"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - collectstatic
            - --noinput
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: release-name-banjo-helm-secret
            - configMapRef:
                name: release-name-banjo-helm-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "hook"
---
# Source: banjo-helm/templates/hooks/job.yaml
# Hook: db-migrate
apiVersion: batch/v1
kind: Job
metadata:
  generateName: release-name-banjo-helm-db-migrate-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: release-name-banjo-helm
    component: hook
    hookName: db-migrate
    environment: ALPHA
    release: release-name
spec:
  activeDeadlineSeconds: 3600
  ttlSecondsAfterFinished: 604800
  template:
    metadata:
      annotations:
        checksum/secret: 66a6fc24b76971f276c49234b716b2b8226b4c72a18511215a54ab9a414b4d53
        checksum/configmap: 3f5505b0f56b1094e754509a8dd06e18d87db0905c755ea4b4ab0cc647f29da3
      labels:
        app: release-name-banjo-helm
        component: hook
        hookName: db-migrate
    spec:
      restartPolicy: "Never"
      serviceAccountName: secret-account
      containers:
        - name: db-migrate
          image: "ghcr.io/example/example:v1.0.1"
          imagePullPolicy: IfNotPresent
          command: 
            - ./manage.py
            - migrate
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: release-name-banjo-helm-secret
            - configMapRef:
                name: release-name-banjo-helm-env-name
          env:
            - name: DJANGO_APP_TYPE
              value: "hook"
---
# Source: banjo-helm/templates/api/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-banjo-helm-api
  labels:
    app: release-name-banjo-helm
    component: api
    environment: ALPHA
    release: release-name
spec:
  ingressClassName: "nginx"
  rules:
    - host: "myapp.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-banjo-helm-api
                port:
                  number: 80
  tls:
    - secretName: my-secret
      hosts:
        - "myapp.example.com"
---
# Source: banjo-helm/templates/extraManifests.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  backup: {}
  enablePDB: true
  instances: 3
  monitoring:
    enablePodMonitor: true
  plugins:
  - isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: aws-s3-store
  storage:
    size: 300Mi
---
# Source: banjo-helm/templates/extraManifests.yaml
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: aws-s3-store
spec:
  configuration:
    destinationPath: s3://my-db-backup/barman/
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: barman-s3-creds
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: barman-s3-creds
    wal:
      compression: gzip
      maxParallel: 4
  retentionPolicy: 30d
---
# Source: banjo-helm/templates/extraManifests.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-daily
spec:
  backupOwnerReference: self
  cluster:
    name: pg-cluster
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: 0 0 0 * * *
  suspend: false
