{{- if .Values.argoHook.enabled }}

{{- range $hookName, $hook := .Values.argoHook.hooks }}

{{- if $hook.enabled }}

---
apiVersion: batch/v1
kind: Job
metadata:
  {{- if $hook.preserveHistory }}
  generateName: {{ template "django-app.fullname" $ }}-{{ $hookName }}-
  {{- else }}
  name: {{ template "django-app.fullname" $ }}-{{ $hookName }}
  {{- end }}
  annotations:
    argocd.argoproj.io/hook: {{ $hook.hook }}
spec:
  template:
    spec:
      restartPolicy: "Never"
      containers:
        - name: {{ $hookName }}
          {{- include "django-app.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.argoHook.image)
              | nindent 10
          }}
          command: {{ toYaml $hook.command | trim | nindent 12 }}
          {{- if $hook.args }}
          args: {{ toYaml $hook.args | trim | nindent 12 }}
          {{- end }}
          resources:
            {{- include "django-app.resourcesConfig"
                (dict "Default" $.Values.argoHook.resources "Override" $hook.resources)
                | nindent 12
            }}
          envFrom:
            {{- include "django-app.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "django-app.envTemplate"
                (dict "Values" $.Values "Type" "hook" )
                | nindent 12
            }}

{{- end }}

{{- end }}

{{- end }}
