{{- if .Values.worker.enabled }}
{{- if .Values.worker.flower.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "banjo.fullname" . }}-celery-flower
  {{- with (include "banjo.appDefaultDeploymentAnnotations" $) -}}{{ . | nindent 2 }}{{- end }}
  labels:
    app: {{ include "banjo.fullname" . }}
    component: worker-flower
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "banjo.fullname" . }}
      component: worker-flower
  template:
    metadata:
      annotations:
        {{- include "banjo.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "banjo.fullname" . }}
        component: worker-flower
        {{- with (include "banjo.appDefaultLabels" $) -}}{{ . | nindent 8 }}{{- end }}
    spec:
      {{- with (include "banjo.appDefaultVolumes" $) -}}{{ . | nindent 6 }}{{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "banjo.serviceAccountName" $ }}
      {{- end }}
      containers:
        - name: worker
          {{- include "banjo.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.worker.flower.image)
              | nindent 10
          }}
          command:
            {{- toYaml .Values.worker.flower.command | nindent 12 }}
          # TODO: livenessProbe
          resources:
            {{- toYaml .Values.worker.flower.resources | nindent 12 }}
          envFrom:
            {{- include "banjo.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "banjo.envTemplate"
                (dict "Values" $.Values "Type" "worker" )
                | nindent 12
            }}
          {{- with (include "banjo.appDefaultVolumeMounts" $) -}}{{ . | nindent 10 }}{{- end }}

{{- end }}
{{- end }}
