{{- if .Values.argoHook.enabled }}

{{- range $hookName, $hook := .Values.argoHook.hooks }}

{{- if $hook.enabled }}

---
# Hook: {{ $hookName }}
apiVersion: batch/v1
kind: Job
metadata:
  {{- if $hook.preserveHistory }}
  generateName: {{ template "banjo.fullname" $ }}-{{ $hookName }}-
  {{- else }}
  name: {{ template "banjo.fullname" $ }}-{{ $hookName }}
  {{- end }}
  annotations:
    argocd.argoproj.io/hook: {{ $hook.hook }}
spec:
  template:
    metadata:
      annotations:
        {{- include "banjo.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "banjo.fullname" $ }}
        component: argo-hooks
        {{- with (include "banjo.appDefaultLabels" $) -}}{{ . | nindent 8 }}{{- end }}
    spec:
      restartPolicy: "Never"
      {{- with (include "banjo.appDefaultVolumes" $) -}}{{ . | nindent 6 }}{{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "banjo.serviceAccountName" $ }}
      {{- end }}
      containers:
        - name: {{ $hookName }}
          {{- include "banjo.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.argoHook.image)
              | nindent 10
          }}
          command: {{ toYaml $hook.command | trim | nindent 12 }}
          {{- if $hook.args }}
          args: {{ toYaml $hook.args | trim | nindent 12 }}
          {{- end }}
          resources:
            {{- include "banjo.resourcesConfig"
                (dict "Default" $.Values.argoHook.resources "Override" $hook.resources)
                | nindent 12
            }}
          envFrom:
            {{- include "banjo.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "banjo.envTemplate"
                (dict "Values" $.Values "Type" "hook" )
                | nindent 12
            }}
            {{- with $hook.env }}
            {{- range $envKey, $envVal := . }}
            - name: {{ $envKey }}
              value: {{ tpl $envVal $ | quote }}
            {{- end }}
            {{- end }}
          {{- with (include "banjo.appDefaultVolumeMounts" $) -}}{{ . | nindent 10 }}{{- end }}

{{- end }}

{{- end }}

{{- end }}
