{{- if .Values.worker.enabled }}

{{- range $queue_name, $config := .Values.worker.queues }}
{{- if $config.enabled }}

---
# Queue: {{ $queue_name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "banjo.fullname" $ }}-worker-{{ $queue_name }}
  {{- with (include "banjo.appDefaultDeploymentAnnotations" $) -}}{{ . | nindent 2 }}{{- end }}
  labels:
    app: {{ include "banjo.fullname" $ }}
    component: worker
    queue: {{ $queue_name }}
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
spec:
  {{- if not (eq $config.replicaCount nil) }}
  replicas: {{ $config.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "banjo.fullname" $ }}
      component: worker
      queue: {{ $queue_name }}
  template:
    metadata:
      annotations:
        {{- include "banjo.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "banjo.fullname" $ }}
        component: worker
        queue: {{ $queue_name }}
        {{- with (include "banjo.appDefaultLabels" $) -}}{{ . | nindent 8 }}{{- end }}
    spec:
      {{- with (include "banjo.appDefaultVolumes" $) -}}{{ . | nindent 6 }}{{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "banjo.serviceAccountName" $ }}
      {{- end }}
      containers:
        - name: worker
          command:
            {{- toYaml $.Values.worker.queueCommandPrefix | nindent 12 }}
            {{- toYaml $config.celeryArgs | nindent 12 }}
          {{- include "banjo.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.worker.image)
              | nindent 10
          }}
          # TODO: livenessProbe
          resources:
            {{- include "banjo.resourcesConfig"
                (dict "Default" $.Values.worker.queueDefaultResources "Override" $config.resources)
                | nindent 12
            }}
          envFrom:
            {{- include "banjo.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "banjo.envTemplate"
                (dict "Values" $.Values "Type" "worker" )
                | nindent 12
            }}
            {{- with $config.env }}
            {{- range $envKey, $envVal := . }}
            - name: {{ $envKey }}
              value: {{ tpl $envVal $ | quote }}
            {{- end }}
            {{- end }}
          {{- with (include "banjo.appDefaultVolumeMounts" $) -}}{{ . | nindent 10 }}{{- end }}

{{- end }}

{{- end }}

{{- end }}
