kind: Secret
apiVersion: v1
metadata:
  name: {{ template "django-app.secretname" . }}
  labels:
    app: {{ include "django-app.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  # secrets
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ tpl $value $ | quote }}
  {{- end }}
